# Generated by Django 5.1.4 on 2025-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_management', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
