# Generated by Django 5.1.4 on 2025-01-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_management', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
